version: 2
jobs:
  checkout_code:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/react-native-google-autocomplete
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-native-google-autocomplete
      - restore_cache:
          keys:
            - 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - 'yarn-cache-{{ .Branch }}'
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  test_and_report:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/react-native-google-autocomplete
    steps:
      - attach_workspace:
          at: ~/react-native-google-autocomplete
      - run: yarn test:coverage
      - run: yarn report
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/react-native-google-autocomplete
    steps:
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: .
  release:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/react-native-google-autocomplete
    steps:
      - attach_workspace:
          at: ~/react-native-google-autocomplete
      - run: yarn start release || true
workflows:
  version: 2
  test_and_release:
    jobs:
      - checkout_code
      - test_and_report:
          requires:
            - checkout_code
      - build:
          requires:
            - test_and_report
      - release:
          requires:
            - build
          filters:
            branches:
              only: master